version: "3.9"

services:
  frontend-green:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend-green
    ports:
      - "3002:80"
    restart: always

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-green
    environment:
      - NODE_ENV=production
    ports:
      - "4002:4000"
    restart: always
