version: "3.9"

services:
  frontend-blue:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend-blue
    ports:
      - "3001:80"
    restart: always

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-blue
    environment:
      - NODE_ENV=production
    ports:
      - "4001:4000"
    restart: always
